filebeat.inputs:
  - type: docker
    containers.ids:
      - '*'  # Collect logs from all Docker containers
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true  # Flatten JSON logs to make them more accessible
    json.add_error_key: true  # Add an error key if JSON parsing fails
    multiline.pattern: '^[[:space:]]'
    multiline.negate: false
    multiline.match: after
    processors:
      - add_docker_metadata: ~  # Add Docker metadata to the logs

output.logstash:
  hosts: ["logstash:5044"]  # Send logs to Logstash service
